### ISSUE TITLE
Mobile VO Read through interrupted unevenly when even happens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#352] opened 2020-05-28 19:39 UTC
**Device**
iPad
**OS**
iPadOS 13
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/503. Seen with mobile VO, may occur generally but looked ok on NVDA. May be a general mobile VO issue
When reading through the scene description, if an alert about a molecule or photon comes up, the reading is interrupted, but not cleanly. Words are cut off and lost, both in the interrupted scene description and in the alert. This leads to disjointed and sometimes hard to understand descriptions. By contrast, NVDA seems to wait for a break in the description script, read the alerts, and then continue with the description.
**Visuals**
https://drive.google.com/file/d/1-9WkoeT5R1yzgiLL6WAzl7kbCU7ZGSdy/view?usp=sharing

**Comment by terracoda** [comment] 2020-06-02 15:35
@KatieWoe, From the video I don't hear what is problematic? 
With sims like MAL that have an active state that continuously updates (this is our first sim with this behaviour), I'm not sure we can address any issues related to simultaneous responses and with simultaneous changes happening in the state descriptions.

We do not want the responses (alerts) to pile up and get stale. 

I think it might be up to the learner to sort out what they want to attend to - what they are reading in the State Descriptions or what the sim is saying in response to them leaving the photons on. 

I asked about this - or at least what I think you are demonstrating - in two interviews and one participant said it was strange that her cursor kept moving (this was because the content was changing), and she was trying to read the changing content. 

And another participant said she was used to multi-tasking, and described it like getting an notification about an incoming email while she was reading a document. She wasn't bothered by it at all.

@KatieWoe, is this what you mean by "uneven interruption"?

**Comment by terracoda** [comment] 2020-06-02 18:48
If I got your example correct, we think this is expected behaviour and will close the issue.

**Closed by terracoda** 2020-06-02 18:48 UTC
Labels: type:a11y-bug

**Comment by KatieWoe** [comment] 2020-07-16 21:21
Noting this issue in https://github.com/phetsims/QA/issues/513, in an instance where the scene description was cut off, but restarted without ever reading the alert.
