### ISSUE TITLE
Step Forward gets stuck when Enter Key is held down

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#337] opened 2020-05-05 17:03 UTC
In last Friday's interview with JAWS consultant we noticed the Step Forward interaction gets stuck when holding down the Enter Key.

Focus also slipped to off the Step Forward button to Light Source button.

**Comment by jessegreenberg** [comment] 2020-05-05 17:12
Reviewing the playback of what happened, it looks like JAWS + Firefox was being used.

**Comment by terracoda** [comment] 2020-05-05 17:15
Note that we were using JAWS and Firefox in the interview instead of Chrome.

**Comment by terracoda** [comment] 2020-05-05 17:16
Let's just verify these things do not happen in Chrome.

**Comment by jessegreenberg** [comment] 2020-05-05 20:04
OK, I confirmed that this is happening with Chrome and JAWS.

**Comment by jessegreenberg** [comment] 2020-05-05 20:12
I verified that this is just the behavior of JAWS for all buttons. It is happening for this basic HTML too
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>title</title>
</head>
<body>

<button id="button">Press Me!</button>
<ul id="output"></ul>

</body>
<script>
  const button = document.getElementById( 'button' );
  const list = document.getElementById( 'output' );

  button.addEventListener( 'click', event => {
    const newElement = document.createElement( 'li' );
    newElement.textContent = 'Click Received';
    list.appendChild( newElement );
  } );
</script>
</html>
```

**Comment by jessegreenberg** [comment] 2020-05-05 20:16
I added this to our AT bug tracker at https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit

Reassigning to @terracoda so you are aware of this result since it came up during an interview. But otherwise I think this can be closed.

**Closed** 2020-05-06 09:15 UTC
Labels: meeting:a11y, status:ready-for-review, type:a11y-bug
