### ISSUE TITLE
Random syllables read out during molecule selection on mobile VO

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#251] opened 2019-12-16 21:44 UTC
**Device**
iPad (6th Gen)
**OS**
iPadOS 13.3
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/461. Found on mobile voice over.
When going through the molecule list on the iPad, either manually or automatically, there are out of place words between the options such as "2" or "linear" depending on what was in the previous option.
**Visual**
https://drive.google.com/file/d/1wip9o5s-NcRN1L5-w7ZLuSg8Pi932Zo2/view?usp=sharing

**Comment by jessegreenberg** [comment] 2019-12-16 22:21
Thanks, that looks strange I will investigate.

**Comment by jessegreenberg** [comment] 2020-05-05 20:37
This is still happening.

**Comment by jessegreenberg** [comment] 2020-05-05 20:39
This is what the HTML looks like
![image](https://user-images.githubusercontent.com/6396244/81113882-e98e5000-8eee-11ea-93d1-2424eb4e685a.png)

The random syllables are the subscript and geometry part of the each item ("2, linear") and ("4, tetrahedral" and so on.

**Comment by jessegreenberg** [comment] 2020-05-05 20:44
I wonder if this is caused by the inner html marking things as subscripts
![image](https://user-images.githubusercontent.com/6396244/81114222-9d8fdb00-8eef-11ea-87db-3f4fdaf58f10.png)

**Comment by jessegreenberg** [comment] 2020-05-05 20:56
Yes, that seems to be what it is. Reading each list item is broken up when reading this
```html
<ul>
  <li>Carbon Monoxide, CO, linear</li>
  <li>Nitrogen, N<sub>2</sub>, linear</li>
  <li>Oxygen, O<sub>2</sub>, linear</li>
  <li>Carbon Dioxide, CO<sub>2</sub></li>
  <li>Ozone, O<sub>3</sub>, bent</li>
</ul>
```

VoiceOver reads "Nitrogen, N", then it takes another gesture to read "2, linear".

**Comment by jessegreenberg** [comment] 2020-05-05 21:00
OK, I verified that it is happening in vanilla list of radio buttons
```html
<ul>
  <li>
    <input type="radio" id="radio-1">
    <label for="radio-1">Carbon Monoxide, CO, linear</label>
  </li>
  <li>
    <input type="radio" id="radio-2">
    <label for="radio-2">Nitrogen, N<sub>2</sub>, linear</label>
  </li>
  <li>
    <input type="radio" id="radio-3">
    <label for="radio-3">Oxygen, O<sub>2</sub>, linear</label>
  </li>
  <li>
    <input type="radio" id="radio-4">
    <label for="radio-4">Carbon Dioxide, CO<sub>2</sub></label>
  </li>
  <li>
    <input type="radio" id="radio-5">
    <label for="radio-5">Ozone, O<sub>3</sub>, bent</label>
  </li>
</ul>
```

So I feel confident that there is nothing to be done about this, this is just how iOS VoiceOver reads subscripts.

**Comment by jessegreenberg** [comment] 2020-05-05 21:02
Added to AT bug tracking document, closing.

**Closed by jessegreenberg** 2020-05-05 21:02 UTC
Labels: type:a11y-bug
