### ISSUE TITLE
Mobile VO jumping around and reading wrong things

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#253] opened 2019-12-16 23:20 UTC
**Device**
iPad 6th Gen
**OS**
iPadOS 13.3
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/461. If you try to start the scene description while something that generates alerts is happening VO will jump around, repeat things, say things that I can't identify, and generally be indescribable until the user interrupts it.
**Steps to Reproduce**
1. With VO on, start a scene that generates alerts
2. Swipe up with 2 fingers to start reading the description

**Visuals**
https://drive.google.com/file/d/1XdiRHZMDJ3Bb9jCvamll6HtPB2ukQg07/view?usp=sharing

**Comment by jessegreenberg** [comment] 2020-05-06 15:09
I just tried this but was not able to reproduce. I think this is the same issue as #237 and #225 which where fixed right around the time of https://github.com/phetsims/QA/issues/461. CLosing this issue.

**Closed by jessegreenberg** 2020-05-06 15:09 UTC
Labels: type:a11y-bug
