### ISSUE TITLE
Can these seemingly unused options be removed?

### ISSUE THREAD

**Issue by samreid** [phetsims/molecules-and-light#115] opened 2015-04-30 17:22 UTC
During #112 I saw this code:

```js
        case PhotonTarget.SINGLE_CO_MOLECULE:
          newMolecule = new CO( this, { initialCenterOfGravityPos: SINGLE_MOLECULE_POSITION } );
          this.activeMolecules.add( newMolecule );
          break;

        case PhotonTarget.SINGLE_CO2_MOLECULE:
          newMolecule = new CO2( this, { initialCenterOfGravityPos: SINGLE_MOLECULE_POSITION } );
          this.activeMolecules.add( newMolecule );
          break;

        case PhotonTarget.SINGLE_H2O_MOLECULE:
          newMolecule = new H2O( this, { initialCenterOfGravityPos: SINGLE_MOLECULE_POSITION } );
          this.activeMolecules.add( newMolecule );
          break;
```

However, the constructors for molecules don't take a second argument.  So can this be removed?  To support #112 I may need to add tandems to these constructors.

**Comment by samreid** [comment] 2015-04-30 17:23
EDIT: in the above comment, when I said "can this be removed", I am referring to the second argument, with initialCenterOfGravityPos.

**Comment by jbphet** [comment] 2015-05-19 20:35
These options should actually be respected.  In the current version of the code, both parameters to the molecule constructors are ignored.  The ```this``` parameter doesn't seem to make any sense to me.  The second parameter should probably be respected, since it will be needed if and when the multi-molecule version of this is needed, which exists in the Java version of the Greenhouse sim.

@jessegreenberg should probably look back at the Java code and figure out if there is something we're missing for the ```this``` parameter.  If not, it should be removed, and then code should be added to the molecule constructors to allow the initial setting of the center of gravity.

**Comment by jessegreenberg** [comment] 2015-05-28 15:48
Molecules used to have options that included initial position and require the PhotonAbsorptionModel for construction.  Passing in the model was a mistake and removed from the constructor after code review.  `this` should not be passed in, I will remove it from the cases in PhotonAbsorptionModel shown above.

It was also decided in code review that Molecules and Light be built without preparing for the Greenhouse sim.  This is why options including initial position were removed from the Molecule constructors.  Because of this, I think these options should be removed for now.

I think I just forgot to remove these parameters after changing the constructors during code review.  Sorry about that, I will remove them.

**Comment by jessegreenberg** [comment] 2015-05-28 16:38
The model and optional initial position parameter have been removed.  Reassigning to @jbphet for review since he has familiarity with this sim and is familiar with the relationship between Molecules and Light and the Greenhouse gas sim.

**Comment by jbphet** [comment] 2015-05-28 20:35
I went ahead and added the option for specifying the initial position of the molecules.  I figured it was fairly quick and easy to do while this is all fresh in our minds, and would take longer when this is adapted to support the Greenhouse simulation.  This was unit tested and regression tested and seemed to work just fine.  Closing.

**Closed by jbphet** 2015-05-28 20:35 UTC
