### ISSUE TITLE
TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by samreid** [phetsims/molecules-and-light#137] opened 2016-08-10 18:07 UTC
While testing https://github.com/phetsims/beers-law-lab/issues/182 I ran

```
http://localhost/chipper/test-server/test-sims.html?loadOnly
```

and observed:

```
Uncaught TypeError: Cannot read property 'show' of undefined
TypeError: Cannot read property 'show' of undefined
    at listener (http://localhost/molecules-and-light/js/moleculesandlight/view/MoleculesAndLightScreenView.js?bust=1470852132459:154:28)
    at http://localhost/sun/js/buttons/PushButtonModel.js?bust=1470852132459:130:9
    at Array.forEach (native)
    at PushButtonModel.fire (http://localhost/sun/js/buttons/PushButtonModel.js?bust=1470852132459:129:12)
    at http://localhost/sun/js/buttons/PushButtonModel.js?bust=1470852132459:73:25
    at Array.onValueObserver (http://localhost/axon/js/Property.js?bust=1470852132459:332:13)
    at Emitter.emit2 (http://localhost/axon/js/Emitter.js?bust=1470852132459:139:49)
    at Property._notifyObservers (http://localhost/axon/js/Property.js?bust=1470852132459:146:29)
    at Property._setAndNotifyObservers (http://localhost/axon/js/Property.js?bust=1470852132459:134:14)
    at Property.set (http://localhost/axon/js/Property.js?bust=1470852132459:102:16)
```

This may be a test harness or axon problem, but I'm not sure at the moment, so I've created the issue here.  Launching 

http://localhost/molecules-and-light/molecules-and-light_en.html?ea&brand=phet

Does not revel the problem.  I'll test in the harness again.

**Comment by samreid** [comment] 2016-08-10 18:07
It tested out OK in the harness this time.  Not sure what went wrong, closing.

**Comment by phet-steele** [comment] 2016-11-15 18:16
@samreid @jessegreenberg this error occurred during the 11/15 automated testing:

```
TypeError: Cannot read property 'show' of undefined
    at listener (http://phettest.colorado.edu/molecules-and-light/js/moleculesandlight/view/MoleculesAndLightScreenView.js:154:28)
    at http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js:130:9
    at Array.forEach (native)
    at PushButtonModel.fire (http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js:129:12)
    at Array. (http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js:72:16)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js:139:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js:170:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js:158:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js:126:16)
    at PushButtonModel.set [as down] (http://phettest.colorado.edu/axon/js/PropertySet.js:149:43)
```

**Comment by jonathanolson** [comment] 2016-11-24 03:28
Also occurred on one of my three tests so far tonight.

**Comment by jessegreenberg** [comment] 2016-11-29 20:39
I let this sim fuzz for ~3 hours and it started to bog down from #136, but I never hit this issue.

**Comment by jonathanolson** [comment] 2017-01-05 21:33
This has occurred 10 times in automated testing in the last few hours, 90% of which were in the built mode.

**Comment by jonathanolson** [comment] 2017-02-03 01:05
And again today:
```
molecules-and-light : fuzz : require.js : load
Uncaught TypeError: Cannot read property 'show' of undefined
TypeError: Cannot read property 'show' of undefined
    at listener (http://localhost/snapshot-1486082540700/molecules-and-light/js/moleculesandlight/view/MoleculesAndLightScreenView.js?bust=1486083185725:154:28)
    at http://localhost/snapshot-1486082540700/sun/js/buttons/PushButtonModel.js?bust=1486083185725:139:9
    at Array.forEach (native)
    at PushButtonModel.fire (http://localhost/snapshot-1486082540700/sun/js/buttons/PushButtonModel.js?bust=1486083185725:138:12)
    at Array.<anonymous> (http://localhost/snapshot-1486082540700/sun/js/buttons/PushButtonModel.js?bust=1486083185725:81:16)
    at Emitter.emit2 (http://localhost/snapshot-1486082540700/axon/js/Emitter.js?bust=1486083185725:147:49)
    at Property._notifyObservers (http://localhost/snapshot-1486082540700/axon/js/Property.js?bust=1486083185725:176:29)
    at Property._setAndNotifyObservers (http://localhost/snapshot-1486082540700/axon/js/Property.js?bust=1486083185725:165:14)
    at Property.set (http://localhost/snapshot-1486082540700/axon/js/Property.js?bust=1486083185725:133:16)
    at Object.up (http://localhost/snapshot-1486082540700/sun/js/buttons/ButtonListener.js?bust=1486083185725:49:38)
Approximately 2/2/2017, 5:42:20 PM
```

**Comment by jessegreenberg** [comment] 2017-02-15 21:42
Ran into this again today, in the built version.

**Comment by zepumph** [comment] 2017-03-09 21:25
I found this is in automated phet-io tests today:

```
molecules-and-light
Uncaught TypeError: Cannot read property 'show' of undefined
TypeError: Cannot read property 'show' of undefined
    at listener (http://localhost/molecules-and-light/js/moleculesandlight/view/MoleculesAndLightScreenView.js?bust=1489094629297:154:28)
    at http://localhost/sun/js/buttons/PushButtonModel.js?bust=1489094629297:142:9
    at Array.forEach (native)
    at PushButtonModel.fire (http://localhost/sun/js/buttons/PushButtonModel.js?bust=1489094629297:141:12)
    at Array. (http://localhost/sun/js/buttons/PushButtonModel.js?bust=1489094629297:84:16)
    at Emitter.emit2 (http://localhost/axon/js/Emitter.js?bust=1489094629297:147:49)
    at Property._notifyObservers (http://localhost/axon/js/Property.js?bust=1489094629297:210:29)
    at Property._setAndNotifyObservers (http://localhost/axon/js/Property.js?bust=1489094629297:199:14)
    at Property.set (http://localhost/axon/js/Property.js?bust=1489094629297:143:16)
    at Object.up (http://localhost/sun/js/buttons/ButtonListener.js?bust=1489094629297:49:38)

**Comment by jessegreenberg** [comment] 2017-03-21 20:21
@phet-steele is awesome and pointed out that this seems to be happening before the ScreenView is visible.  The issue is that the spectrum window (which extends Dialog) is undefined when we try to show it.

This bit of code looks suspect
```js
      // if the spectrum window hasn't been created yet, try to create it on this frame
      // spectrum window is only created once so that we don't have to draw the nodes in the dialog
      // every time it is shown, which takes a noticeable amount of time on tablets
      if( !this.spectrumWindow ) {
        this.createSpectrumWindow();
      }
```

Why are we trying to create the window in ```step``` rather than the constructor?

**Comment by jessegreenberg** [comment] 2017-03-21 20:23
Very quick fix would be to wrap the "Show Spectrum" button listener with

```js
 if ( self.spectrumWindow ) {
        self.spectrumWindow.show();
  }
```

But we would like to understand why the dialog is not defined yet.

**Comment by phet-steele** [comment] 2017-03-21 20:23
Commit where this was changed, just in case: c2fca3567dac4dfc1ab729684735973493a99157

**Comment by jessegreenberg** [comment] 2017-03-21 20:24
Great, thanks @phet-steele, seems like it was introduced for https://github.com/phetsims/molecules-and-light/issues/135?

**Comment by phet-steele** [comment] 2017-03-21 20:25
> Great, thanks @phet-steele, seems like it was introduced for #135?

Yup.

**Comment by jessegreenberg** [comment] 2017-03-22 20:28
> But we would like to understand why the dialog is not defined yet.

The dialog wasn't defined because Dialog layout requires simBounds to be defined, and it isn't until everything in the sim is constructed.

The fix was to pre-construct the dialog content (for better performance) and create a new dialog with the content once the user opens the dialog.

@phet-steele this should be fixed with the above commit.  I tried refreshing the sim ~10 times and did not produce the error. Let me know if you see it again!

**Closed by jessegreenberg** 2017-03-22 20:28 UTC
Labels: type:automated-testing
