### ISSUE TITLE
Sound: Close dialog sound on Keyboard Shortcuts dialog?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#258] opened 2019-12-17 20:09 UTC
@jbphet, this is our first sim with a dialog that can be popped up from within the Sim Area.

I just noticed that the close dialog sound for the Light Spectrum Dialog also plays when I close the Keyboard Shortcuts dialog.

I think this is a mistake (not 100% sure, though). I think it is a mistake because there is no open dialog sound for the Keyboard Shortcuts pop-up button.

It might be prudent to either remove the close dialog sound from the Keyboard Shortcuts dialog or add the open sound - whichever makes most sense to you.

This would depend on whether or not there has been a decision to sonify or not to sonify the elements in the navigation bar. There is also no sound for the Mute Sound toggle button nor is there a sound for the PhET Menu pop-up button.

**Comment by jbphet** [comment] 2019-12-17 20:37
> I think this is a mistake (not 100% sure, though).

It's not really a mistake.  We have added common UI sounds to master, and the close button is playing the generic push button sound.  The nav bar buttons are a different type of button and, so far, we have not added a common sound to those.  It would be fairly straightforward to turn off the sound for closing the button dialog.  It would be easy, though probably more controversial, to add sounds to the nav bar buttons.  I'm up for either, but the former would be quicker.

I'm going to add @emily-phet as an assignee so that she can log her opinion, and I'll base my next steps on what she and @Ashton-Morris have to say.

**Comment by terracoda** [comment] 2019-12-17 20:41
Since, we have the first review of this sim tomorrow, I am in favour of removing the sound on that dialog.

**Comment by KatieWoe** [comment] 2020-01-06 18:31
Quick note for when I was testing https://github.com/phetsims/QA/issues/464.
When you click the x to get out of the keyboard nav instructions it makes a noise. If you click outside the box it doesn't. This seems a bit inconsistent, but not bad enough that I think a fix is needed. Noting here for review.

**Comment by jbphet** [comment] 2020-01-14 21:23
We discussed this in a review meeting on 1/1/2020, and concluded that we should integrate specific sounds for open and close of dialogs and override the default button sound.  @Ashton-Morris is going to review the combo box open/close sounds and make a recommendation as to whether to use those or create new, dialog-specific sounds.

**Comment by Ashton-Morris** [comment] 2020-01-16 16:34
After review I feel that the combo box open and close sounds will fit nicely. I have added the files in our Sounds folder for GFL for easy access as well. @jbphet

**Comment by jbphet** [comment] 2020-01-22 19:49
I have added sounds for dialog open and close.  I'm going to assign this issue to @Ashton-Morris to review as the general sound designer, and to @terracoda since she initially brought this to our attention.  

@Ashton-Morris - If you and @terracoda approve, please demonstrate the sound in the next general UI sound design meeting and see if there are any objections and note the results here (I'll be away).  If everyone is okay with it, feel free to simply close this issue.

The sound can be experienced through the "Show Light Spectrum" dialog or any of the dialogs available through the PhET menu on this dev version: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.23/phet/molecules-and-light_en_phet.html.

**Comment by emily-phet** [comment] 2020-01-22 19:59
@terracoda @Ashton-Morris 
Just played around with this, a few thoughts:
- the sound feels like it has a slight delay, like it happens after the visual change rather than both imitating at the same time. This may have a quirky device/browser dependence (I'm on my Mac using Safari), but if not, would be nice to figure out why that's happening.
- Each sound feels slightly long to me
- I'm not sure if it's possible, but in my mind it would be nice to convey the nice "open" / "close" sound through a single tone (@ashton - kind of like what I liked for the nav bar / home screen buttons.

Overall, I thought they were very nice, and if you were all good with them, that's fine with me as well. Aside from checking if the sound feels delayed to others and not just me, the comments above are just minor thoughts to consider.

**Comment by Ashton-Morris** [comment] 2020-01-23 00:02
I think it sounds really good and fits perfectly with the visuals. 

I can't see any improvements needed but I can experiment with a single tone via @emily-phet suggestion before our next meeting.

**Comment by emily-phet** [comment] 2020-03-12 17:00
This is good to go - let's go with what is currently there. 
@jbphet I'm assuming what's in there now is what was positively reviewed above. Please confirm and close.

**Comment by terracoda** [comment] 2020-03-12 17:17
I like the sound. I don't remember any direct comments from the recent interviews that took place. Two interviewees did indeed open the dialog, and I have no negative feedback.

**Comment by terracoda** [comment] 2020-03-12 17:19
@jbphet, see @emily-phet https://github.com/phetsims/molecules-and-light/issues/258#issuecomment-598299968

**Comment by jbphet** [comment] 2020-03-14 15:39
> @jbphet I'm assuming what's in there now is what was positively reviewed above. Please confirm and close.

Yep, I can confirm that.  Closing.

**Closed by jbphet** 2020-03-14 15:39 UTC
Labels: design:a11y, dev:sonification
