### ISSUE TITLE
Slight Quirks in text in iFrame and String Tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molecules-and-light#121] opened 2015-08-19 18:24 UTC
Test device: 

Operating System: Windows 7

Browser: IE 11

Problem description: The are overlaying issues in the CO2 and NO2 text. This appears in the iFrame and in both the double and Extremely Long String tests.

Steps to reproduce: Open sim in iFrame or perform string test.

Severity: Minor

Screenshots:
![img_6752](https://cloud.githubusercontent.com/assets/12610678/9365132/212110cc-466d-11e5-91a4-a3e47e91b0c3.JPG)

Troubleshooting information (do not edit):
  
Name: ‪Molecules and Light‬

URL: http://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.2.0/molecules-and-light_en.html

Version: 1.1.0-dev.2 2015-08-14 21:27:47 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

Language: en-US

Window: 1651x944

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"HEAD"},"axon":{"sha":"5be7fe04","branch":"HEAD"},"babel":{"sha":"ab57b57d","branch":"tests"},"brand":{"sha":"0329ea5a","branch":"HEAD"},"chipper":{"sha":"ae27246d","branch":"HEAD"},"dot":{"sha":"e34c6b2c","branch":"HEAD"},"joist":{"sha":"0f8e76c7","branch":"HEAD"},"kite":{"sha":"24978146","branch":"HEAD"},"molecules-and-light":{"sha":"1af27e65","branch":"HEAD"},"nitroglycerin":{"sha":"c6f79ce4","branch":"HEAD"},"phet-core":{"sha":"8e31808c","branch":"HEAD"},"phetcommon":{"sha":"89a44d2c","branch":"HEAD"},"scenery":{"sha":"be4fc88f","branch":"HEAD"},"scenery-phet":{"sha":"78082cb3","branch":"HEAD"},"sherpa":{"sha":"1759eade","branch":"HEAD"},"sun":{"sha":"1320a557","branch":"HEAD"}}

**Comment by jessegreenberg** [comment] 2015-08-20 16:58
I just reproduced this issue on Bates test machine, Windows 7, IE10.  Screenshots below -

At sim start up, chemical formula text looks horribly stretched out:
![expanded_text](https://cloud.githubusercontent.com/assets/6396244/9389747/d205da14-4729-11e5-82c3-df249a1bb69b.PNG)

At first interaction with sim (like mouse over any component) text corrects itself, but chemical formuls can still overlap
![corrected_text](https://cloud.githubusercontent.com/assets/6396244/9389759/e6c38762-4729-11e5-97bd-815d6f95497d.PNG)

**Comment by jessegreenberg** [comment] 2015-08-20 23:38
I did not realize that this issue was present for ALL strings on sim start up for stringTest=double.  Just tested on Windows 7 IE11 and observed the following behavior:

![mal_double_broken](https://cloud.githubusercontent.com/assets/6396244/9398236/f83635de-4761-11e5-93c5-3331f85ca8bd.PNG)

Again, text readjusts once the user interacts with the sim.  So this is most likely not isolated to Molecules and Light.

**Comment by jessegreenberg** [comment] 2015-08-20 23:39
Observe the following for chemical formulas in acid-base-solutions:

![acid-base-solutions](https://cloud.githubusercontent.com/assets/6396244/9398265/622a018c-4762-11e5-8498-a99c36cb2fa3.PNG)

**Comment by jessegreenberg** [comment] 2015-08-20 23:41
It looks like stringTest=double breaks text for all sims in Internet Explorer.  Moving issue to scenery for now.

**Comment by jessegreenberg** [comment] 2015-08-24 23:24
This was fixed in https://github.com/phetsims/scenery/issues/455, issue is no longer present in IE:

![symbols fixed](https://cloud.githubusercontent.com/assets/6396244/9455094/e451c166-4a84-11e5-9f0e-d3d0951f2ee9.PNG)

![string_test_fixed](https://cloud.githubusercontent.com/assets/6396244/9455097/e7a0745c-4a84-11e5-93ea-ed8a9e00fe66.PNG)

Closing.

**Closed by jessegreenberg** 2015-08-24 23:24 UTC
