### ISSUE TITLE
"Light Spectrum" dialog is not centered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecules-and-light#135] opened 2016-07-07 20:01 UTC
Mac OS X 10.11.5 + Chrome latest.  Noticed in master b7f284fb02195f7865d751237113dc39f1a4f6a3.

When the "Show Light Spectrum" button is pressed, the dialog that opens is supposed to be centered, but it comes up in the upper-left corner (see screenshot).  If the browser window is resized, then the dialog moves to being centered.

![screenshot_46](https://cloud.githubusercontent.com/assets/3046552/16667692/0ff4ccee-444b-11e6-900a-3bbae301284f.png)

**Comment by pixelzoom** [comment] 2016-07-07 20:01
I have not tested on other platforms, but @ariel-phet reproduced this on Win+Chrome.

**Comment by pixelzoom** [comment] 2016-07-07 20:02
Problem also reproduced on Mac OS X + Safari + Firefox.

**Comment by jessegreenberg** [comment] 2016-07-08 18:01
Caused by changes that came out of https://github.com/phetsims/joist/issues/329, but the issue is in SpectrumWindow.  For some reason, the SpectrumWindow dialog had a custom layout function which was unnecessary and did not set layout at the correct time.

**Comment by jessegreenberg** [comment] 2016-07-08 18:01
Above commit fixes the issue. Closing.

**Closed by jessegreenberg** 2016-07-08 18:01 UTC
