### ISSUE TITLE
Make it sound like visible light caused a molecule to break apart

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#244] opened 2019-12-13 20:53 UTC
**Device:**
Mac Book
**OS:**
10.15
**Browser:**
Safari
**Problem Description:**
For https://github.com/phetsims/QA/issues/461. Found using Mac VO. This is a more general problem with moving through the types of light emissions quickly, but the situation described is the easiest to see. The order of priority for reading alerts can cause confusion as to what type of light caused a molecule's behavior. When you move across light emission types quickly, it is possible for a photon emitted by one of them, but the effect to be read after a new light emission. This makes it sound like the wrong type of light caused the behavior.

**Steps to Reproduce:**
1. Turn light on with visible light
2. Switch molecule to ozone
3. Go back to light selection and quickly move to and from UV, so only one photon is released.
4. Listen

**Video:**
https://drive.google.com/file/d/16QKB06D4-jPIycQiqrEfE3hO-kAKw4yg/view?usp=sharing

**Comment by jessegreenberg** [comment] 2019-12-13 20:58
Thanks @KatieWoe, I have encountered this before too. I don't think this is a bug but more a result of the current design so it would be good to hear from @Matthew-phet and @terracoda if anything should be done about this.

The issue is that it is possible to change photon wavelength while the previous photons are still in the observation window. So "Ultraviolet" wavelength can be selected while an infrared photon is to the left of the molecule. Then the infrared photon interacts with the molecule while "Ultraviolet" is selected.

@terracoda @Matthew-phet what (if anything) should be done about this?

**Comment by terracoda** [comment] 2019-12-14 02:08
I have noticed this too and think we just have to accept this odd transition period - at least for now. Though this something we should discuss in design meeting. 

I will mark for meeting topic.

**Comment by terracoda** [comment] 2020-02-03 13:22
I think we discussed this at a meeting. We'll keep an eye on this as we do more interviews.

**Comment by terracoda** [comment] 2020-03-17 23:23
@jessegreenberg, I think we addressed this issue by having a a change in light source, reset the photons, clearing all non-absorbed photons from the screen.

Do you think we can close?

**Comment by jessegreenberg** [comment] 2020-03-24 23:21
Indeed, this has been addressed with #288! Closing.

**Closed by jessegreenberg** 2020-03-24 23:21 UTC
Labels: type:question
