### ISSUE TITLE
CT Cannot read properties of null (reading 'constructor')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#394] opened 2023-05-09 18:33 UTC
```
molecules-and-light : fuzz : unbuilt : listenerOrderRandom
http://127.0.0.1/continuous-testing/ct-snapshots/1683652947012/molecules-and-light/molecules-and-light_en.html?continuousTest=%7B%22test%22%3A%5B%22molecules-and-light%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1683652947012%22%2C%22timestamp%22%3A1683654770758%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught TypeError: Cannot read properties of null (reading 'constructor')
TypeError: Cannot read properties of null (reading 'constructor')
at constructor (MoleculeUtils.js:117:56)
at getGeometryLabel (MicroObservationWindow.js:233:32)
at listener (TinyEmitter.ts:119:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:65:10)
at set (RectangularRadioButton.ts:139:50)
at listener (TinyEmitter.ts:119:8)
at emit (Emitter.ts:58:21)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 11:22:27 AM
```

**Comment by jbphet** [comment] 2023-09-29 21:01
I reproduced this error while working on https://github.com/phetsims/molecules-and-light/issues/398 by using random listener order and the seed shown in that issue.  Specifically, the URL used was http://localhost:8080/molecules-and-light/molecules-and-light_en.html?brand=phet&ea&fuzz&listenerOrder=random(514106).  After close examination of the internal state of the sim when the assert was hit, I could see that the problem was that `PhotonAbsorptionModel.targetMolecule` had not been updated after the photon target ( `PhotonAbsorptionModel.photonTargetProperty`) was changed via a button press.  I did some closer examination of the model code, and it seems like there are definitely some portions that assume a certain order of updates, so I added (locally) the `hasListenerOrderDependencies` flag to  `PhotonAbsorptionModel.photonTargetProperty`.  With this change in place I was able to run the fuzz testing for ~15 minutes with no problems.  I'm going to go ahead and commit this change and see if this issue disappears from CT.

**Comment by jbphet** [comment] 2023-09-29 21:14
For reference, here's a screenshot of the molecules-and-light row on CT.  There is a fair amount of red, and I've looked at most of these errors, and they are fairly evenly split between this issue and https://github.com/phetsims/molecules-and-light/issues/398.

![image](https://github.com/phetsims/molecules-and-light/assets/3082831/c1d65739-5e4b-475b-ba91-00e19250a178)

**Comment by jbphet** [comment] 2023-10-04 18:55
The change committed about seems to fix things in the unbuilt version, but I'm still seeing it every once in a long while on the built version, so I'm not going to close it quite yet.  Here's a current screenshot of CT for this sim:

![image](https://github.com/phetsims/molecules-and-light/assets/3082831/61d50095-70d8-4b66-933e-555cd7b11f78)

**Comment by jbphet** [comment] 2023-10-13 20:25
CT is green as far as the eye can see, so I think it is now safe to close this.

![image](https://github.com/phetsims/molecules-and-light/assets/3082831/bebd36ef-5c90-4a53-bb9c-dbef3d0dc3d9)

**Closed by jbphet** 2023-10-13 20:25 UTC
Labels: type:automated-testing
