### ISSUE TITLE
Command + mouse wheel on macOS

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/molecules-and-light#208] opened 2019-09-10 21:54 UTC
For https://github.com/phetsims/QA/issues/419.

I was trying to do command + mouse wheel to zoom in/out on my MacBook Air, so I plugged in a mouse. I then realized that in the default macOS accessibility settings, you can't do command + mouse wheel to zoom in/out. No problem, I'll just change that setting in System Preferences like so...

![problem](https://user-images.githubusercontent.com/31285590/64652867-16cb4280-d3e2-11e9-8b67-22ef83b22a11.png)
(Including the screenshot for future internet archaeologists.)

Now I can do command + mouse wheel to zoom in/out, but it seems I have been granted too much zooming power by the technology gods...

![issue](https://user-images.githubusercontent.com/31285590/64652963-5e51ce80-d3e2-11e9-914a-d7c12880064a.gif)

Happens on Chrome and Safari.

Is this a problem?

**Comment by jessegreenberg** [comment] 2019-09-11 15:24
Thats a lot of zoom! It appears that you are zooming in on the entire screen since the mouse is getting larger too. So I wonder if this would happen outside of the sim/browser too and is therefore Apples intended behavior. Ill take a look.

**Comment by jessegreenberg** [comment] 2019-10-01 14:18
Talked with @terracoda and we decided that it would be great to support this.

**Comment by jessegreenberg** [comment] 2019-10-08 04:02
OK, I can see this on my laptop too. This is actually the intended behavior. This is the amount of zoom supported by the OS and it allows so much because it is a dedicated accessibility tool. The zoom is not confined to the browser and has nothing to do with the Sim, you can zoom that far into the desktop or task bar as well.

Closing.

**Closed by jessegreenberg** 2019-10-08 04:02 UTC
Labels: dev:a11y, type:a11y-bug
