### ISSUE TITLE
Some observations are hidden

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecules-and-light#247] opened 2019-12-13 23:30 UTC
For https://github.com/phetsims/QA/issues/461. Found in MacOS VO.
I noticed that, depending on what happened to the molecule last, the observations given during the scene description can change. For instance, when microwaves are used on carbon monoxide it will either describe it absorbing and spinning in one direction or another, or it will describe it no longer spinning and releasing a photon in some direction. Since (as far as I know) students aren't likely to listen to this multiple times I suggest combining the statement in cases like this, so the full behavior can be observed. I also noticed, but am a bit less concerned, that things like the direction of spin/release of photon changes and students may get the impression that it is always in the way they heard it.
![changingobservations](https://user-images.githubusercontent.com/41024075/70838508-de167d00-1dc5-11ea-89f4-ed2968d9882e.gif)

**Comment by jessegreenberg** [comment] 2019-12-13 23:46
Thanks @KatieWoe, there are two points to this issue:

> I also noticed, but am a bit less concerned, that things like the direction of spin/release of photon changes and students may get the impression that it is always in the way they heard it.

I assume you are referring to the alerts. In the first alert we hear "Molecule rotates clockwise" then afterward we hear "clockwise" only.  This is out of date with the current design doc, sorry. We decided to remove the direction entirely from this alert because it isn't important to the learning. Ill make this change.

> Since (as far as I know) students aren't likely to listen to this multiple times I suggest combining the statement in cases like this, so the full behavior can be observed.

It is true, we don't expect students to find this frequently while the sim is playing. Instead, the alerts should convey what is happening. However, we expect it may be helpful to students to read this dynamic paragraph when the sim is paused and they are stepping slowly through time. We currently think of the PDOM as an accurate snapshot of what is shown visually. But listing what has happened would make it easy for the user to review independent of time. 

@terracoda can you please review @KatieWoe's thought about this?

**Comment by KatieWoe** [comment] 2019-12-13 23:52
Making note that this is not the only combination I have noticed this in.
I don't think it is in the alerts, you can see it talk about clockwise/counterclockwise in the blue scene description.

**Comment by jessegreenberg** [comment] 2019-12-14 00:05
> I don't think it is in the alerts, you can see it talk about clockwise/counterclockwise in the blue scene description.

I see. So is the concern that they may find this paragraph once and hear it say "clockiwse" and even though it may say "counterclockwise" in the future there is a chance that they will never find it?

**Comment by terracoda** [comment] 2019-12-14 01:48
I think it is awesome that you notice these subtle differences @KatieWoe. 
For now this is a design choice for brevity, and the direction is not critical to learning goals. 
We will be getting some more feedback next week.

Student can and do read the state descriptions more than once. The deepest exploration would normally mean going between reading the state, making changes and reading the states again. Blind users often switch between reading the state and making changes (getting responses). The can’t hear both at the same time, but they can go from on to the other very easily.

**Comment by terracoda** [comment] 2019-12-14 01:50
This is not a bug, but a feature of getting slightly different descriptions depending when you are reading and when you are interacting.

**Comment by terracoda** [comment] 2019-12-14 11:11
@KatieWoe, again, thanks for your comments...like the Jesse mentioned the content in the blue column is a snap shop.  It is not read out automatically to the learner like the content in the orange box is. This sim is a bit challenging as it can keep changing even as the learner is reading through the state descriptions, making the changing details seem like responses (or alerts) that are automatically read out. 

Ideally these finer details about counter-clockwise and clockwise, stretching and contracting, will be providing when using the Step button which is not yet fully implemented.

We will be asking about this in interviews.

**Comment by jessegreenberg** [comment] 2019-12-17 22:29
> We decided to remove the direction entirely from this alert because it isn't important to the learning. Ill make this change.

This is done in the above commit.

**Comment by terracoda** [comment] 2020-04-17 16:41
Many changes to the design have been made since interviews, including a bunch of refined slow motion, and step forward responses.
Closing this issue as descriptions of rotation and direction have been addressed.

**Closed by terracoda** 2020-04-17 16:41 UTC
Labels: design:a11y, type:a11y-bug, type:question
